workflows:
  build-ipa-only:
    name: Export IPA from Xcode Project
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Build IPA
        script: |
          xcodebuild -project "build/Unity-iPhone.xcodeproj" \
            -scheme Unity-iPhone \
            -configuration Release \
            -archivePath build/Unity.xcarchive \
            archive

          xcodebuild -exportArchive \
            -archivePath build/Unity.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa_unsigned \
            -allowProvisioningUpdates

    artifacts:
      - build/ipa_unsigned/*.ipa
