workflows:
  unity-ios-build:
    name: Build Unity Project for iOS
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        UNITY_VERSION: 2022.3.6f1
      xcode: latest
      cocoapods: default
      node: 16.14.2

    scripts:
      - name: Install Unity
        script: |
          brew tap homebrew/cask
          brew install --cask unity-hub
          echo "⚠️ Bạn cần cài Unity từ Codemagic hoặc link trực tiếp."

      - name: Build Unity project to Xcode
        script: |
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -batchmode -nographics -quit \
            -projectPath . \
            -executeMethod BuildScript.PerformiOSBuild \
            -logFile unity_build.log

      - name: Export IPA (unsigned)
        script: |
          xcodebuild -project ios/Unity-iPhone.xcodeproj \
                     -scheme Unity-iPhone \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $CM_BUILD_DIR/build/Unity.xcarchive \
                     archive

          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/build/Unity.xcarchive \
                     -exportPath $CM_BUILD_DIR/build/export \
                     -exportOptionsPlist exportOptions.plist

    artifacts:
      - build/export/*.ipa
      - unity_build.log
