workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        UNITY_PATH: /Applications/Unity/Hub/Editor/2022.3.62f1/Unity.app/Contents/MacOS/Unity

    scripts:
      - name: Build Xcode project from Unity
        script: |
          $UNITY_PATH -batchmode -nographics -quit -projectPath . -executeMethod BuildScript.BuildIOS

      - name: Export IPA
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner archive -archivePath build/Runner.xcarchive
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/export

    artifacts:
      - build/export/*.ipa
